### PR TITLE
Fix #29 add jobid checks

### LINKED ISSUE #29: Error entering insert mode macvim
screen shot 2018-06-21 at 12 18 51 pm

### PR DESCRIPTION
**Pull request by Shougo**
@dylan-chong Please test it.

### CODE REVIEW

**Comment by Shougo** [comment]
@roxma Can you review/merge it?

Note: I have removed tabs.

**Comment by roxma** [comment]
It looks like the errors in  #29 are triggered when `exit_cb` is called before `err_cb` or `out_cb`.

```
"exit_cb": handler	Callback for when the job ends.  The arguments are the
                        ...
                        ...
			Note that data can be buffered, callbacks may still be
			called after the process ends.
```

vim-hug-neovim-rpc cleanup the job entry when `exit_cb` is called. It doesn't look like a good place to do the cleanup.

I'm wondering, is it better to cleanup the data in `close_cb`?

**Comment by roxma** [comment]
If this PR is merged, we might lose data when `exit_cb` is called before data callbacks.

**Comment by dylan-chong** [comment]
screen shot 2018-06-24 at 7 30 25 pm

After some research Macvim has some annoying problems being compiled with python for some reason. 
In normal Vim, I don't get any problems on the current master or this branch.

Sorry if trying to fix this wasted some of your time

**Comment by Shougo** [comment]
Hm.  It is related error?

https://github.com/Shougo/deoplete.nvim/issues/782

**Comment by Shougo** [comment]
Closed.  Because #31 is better.

**Pull request closed without merging**
