### PR TITLE
Add nvim_list_wins()

### LINKED ISSUE #67: rpc method [nvim_list_wins] not implemented
[vim-hug-neovim-rpc] rpc method [nvim_list_wins] not implemented in pythonx/neovim_rpc
_methods.py

Stacktrace:

[denite] Traceback (most recent call last):

[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\rplugin.py", line 65, in do_map

[denite]     return do_map(ui, args[1], args[2])

[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\ui\map.py", line 20, in do_map

[denite]     return MAPPINGS[name](denite, params)
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\ui\map.py", line 66, in _do_action

[denite]     return denite.do_action(name, is_manual=True)
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\ui\default.py", line 97, in do_action

[denite]     self._denite.do_action(self._context, action_name, candidates)
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\parent.py", line 63, in do_action

[denite]     return self._get('do_action', [context, action_name, targets])
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\parent.py", line 84, in _get
[denite]     return self._put(name, args)
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\parent.py", line 80, in _put
[denite]     return self._child.main(name, args, queue_id=None)  # type: ignore
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\child.py", line 79, in main
[denite]     ret = self.do_action(args[0], args[1], args[2])
[denite]   File "C:\Users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\child.py", line 260, in do_action

[denite]     new_context = (action\['func'](context)
[denite]   File "c:\users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\kind\buffer.py", line 38, in action_preview

[denite]     self._get_preview_window() and
[denite]   File "c:\users\user-name\vimfiles\pack\minpac\start\denite.nvim\rplugin\python3\denite\kind\buffer.py", line 56, in _get_preview_window

[denite]     return bool(next(f ilterfalse(
[denite]   File "C:\Users\user-name\AppData\Local\Programs\Python\Python38\lib\site-packages\pynvim\api\common.py", line 176, in \__iter__

[denite]     items = self._fetch()
[denite]   File "C:\Users\user-name\AppData\Local\Programs\Python\Python38\lib\site-packages\pynvim\api\nvim.py", line 182, in request

[denite]     res = self._session.request(name, *args, **kwargs)
[denite]   File "C:\Users\user-name\AppData\Local\Programs\Python\Python38\lib\site-packages\pynvim\msgpack_rpc\session.py", line 104, in request

[denite]     raise self.error_wrapper(err)
[denite] pynvim.api.common.NvimError: nvim_list_wins not implemented

### PR DESCRIPTION
**Pull request by Shougo**
Fix #67

### CODE REVIEW

**Comment by Shougo** [comment]
@roxma Can you merge it?

**Comment by roxma** [comment]
Merged.
Sorry for the late response

**Comment by Shougo** [comment]
Thank you!  Don't mind.  You seems busy.

**Comment by Shougo** [comment]
Note:  Thank you for the invitation.
vim-hug-neovim-rpc is very important for my plugins.
I keep the development.

**Pull request merged**
